import * as React from 'react';
import { ReactThreeFiber } from '@react-three/fiber';
export declare const Text: React.ForwardRefExoticComponent<Pick<Omit<ReactThreeFiber.Node<import("three").Mesh<import("three").BufferGeometry, import("three").Material | import("three").Material[]>, typeof import("three").Mesh>, ReactThreeFiber.NonFunctionKeys<{
    position?: ReactThreeFiber.Vector3 | undefined;
    up?: ReactThreeFiber.Vector3 | undefined;
    scale?: ReactThreeFiber.Vector3 | undefined;
    rotation?: ReactThreeFiber.Euler | undefined;
    matrix?: ReactThreeFiber.Matrix4 | undefined;
    quaternion?: ReactThreeFiber.Quaternion | undefined;
    layers?: ReactThreeFiber.Layers | undefined;
    dispose?: (() => void) | null | undefined;
}>> & {
    position?: ReactThreeFiber.Vector3 | undefined;
    up?: ReactThreeFiber.Vector3 | undefined;
    scale?: ReactThreeFiber.Vector3 | undefined;
    rotation?: ReactThreeFiber.Euler | undefined;
    matrix?: ReactThreeFiber.Matrix4 | undefined;
    quaternion?: ReactThreeFiber.Quaternion | undefined;
    layers?: ReactThreeFiber.Layers | undefined;
    dispose?: (() => void) | null | undefined;
} & import("@react-three/fiber/dist/declarations/src/core/events").EventHandlers & {
    children: React.ReactNode;
    color?: ReactThreeFiber.Color | undefined;
    fontSize?: number | undefined;
    maxWidth?: number | undefined;
    lineHeight?: number | undefined;
    letterSpacing?: number | undefined;
    textAlign?: "center" | "left" | "right" | "justify" | undefined;
    font?: string | undefined;
    anchorX?: number | "center" | "left" | "right" | undefined;
    anchorY?: number | "bottom" | "top" | "middle" | "top-baseline" | "bottom-baseline" | undefined;
    clipRect?: [number, number, number, number] | undefined;
    depthOffset?: number | undefined;
    direction?: "auto" | "ltr" | "rtl" | undefined;
    overflowWrap?: "normal" | "break-word" | undefined;
    whiteSpace?: "normal" | "overflowWrap" | undefined;
    outlineWidth?: string | number | undefined;
    outlineOffsetX?: string | number | undefined;
    outlineOffsetY?: string | number | undefined;
    outlineBlur?: string | number | undefined;
    outlineColor?: ReactThreeFiber.Color | undefined;
    outlineOpacity?: number | undefined;
    strokeWidth?: string | number | undefined;
    strokeColor?: ReactThreeFiber.Color | undefined;
    strokeOpacity?: number | undefined;
    fillOpacity?: number | undefined;
    debugSDF?: boolean | undefined;
    onSync?: ((troika: any) => void) | undefined;
}, "visible" | "attach" | "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "position" | "up" | "scale" | "rotation" | "matrix" | "quaternion" | "layers" | "dispose" | "type" | "id" | "uuid" | "name" | "parent" | "modelViewMatrix" | "normalMatrix" | "matrixWorld" | "matrixAutoUpdate" | "matrixWorldNeedsUpdate" | "castShadow" | "receiveShadow" | "frustumCulled" | "renderOrder" | "animations" | "userData" | "customDepthMaterial" | "customDistanceMaterial" | "isObject3D" | "onBeforeRender" | "onAfterRender" | "applyMatrix4" | "applyQuaternion" | "setRotationFromAxisAngle" | "setRotationFromEuler" | "setRotationFromMatrix" | "setRotationFromQuaternion" | "rotateOnAxis" | "rotateOnWorldAxis" | "rotateX" | "rotateY" | "rotateZ" | "translateOnAxis" | "translateX" | "translateY" | "translateZ" | "localToWorld" | "worldToLocal" | "lookAt" | "add" | "remove" | "clear" | "getObjectById" | "getObjectByName" | "getObjectByProperty" | "getWorldPosition" | "getWorldQuaternion" | "getWorldScale" | "getWorldDirection" | "raycast" | "traverse" | "traverseVisible" | "traverseAncestors" | "updateMatrix" | "updateMatrixWorld" | "updateWorldMatrix" | "toJSON" | "clone" | "copy" | "addEventListener" | "hasEventListener" | "removeEventListener" | "dispatchEvent" | "color" | keyof import("@react-three/fiber/dist/declarations/src/core/events").EventHandlers | "font" | "material" | "geometry" | "morphTargetInfluences" | "morphTargetDictionary" | "isMesh" | "updateMorphTargets" | "overflowWrap" | "anchorX" | "anchorY" | "onSync" | "fontSize" | "maxWidth" | "lineHeight" | "letterSpacing" | "textAlign" | "clipRect" | "depthOffset" | "direction" | "whiteSpace" | "outlineWidth" | "outlineOffsetX" | "outlineOffsetY" | "outlineBlur" | "outlineColor" | "outlineOpacity" | "strokeWidth" | "strokeColor" | "strokeOpacity" | "fillOpacity" | "debugSDF"> & React.RefAttributes<unknown>>;
