// Automatically generated
const TAB_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "unstable_virtual",
  "rtl",
  "orientation",
  "items",
  "groups",
  "currentId",
  "loop",
  "wrap",
  "shift",
  "unstable_moves",
  "unstable_hasActiveWidget",
  "unstable_includesBaseElement",
  "selectedId",
  "panels",
  "manual",
  "setBaseId",
  "registerItem",
  "unregisterItem",
  "registerGroup",
  "unregisterGroup",
  "move",
  "next",
  "previous",
  "up",
  "down",
  "first",
  "last",
  "sort",
  "unstable_setVirtual",
  "setRTL",
  "setOrientation",
  "setCurrentId",
  "setLoop",
  "setWrap",
  "setShift",
  "reset",
  "unstable_setIncludesBaseElement",
  "unstable_setHasActiveWidget",
  "select",
  "setSelectedId",
  "registerPanel",
  "unregisterPanel",
] as const;
export const TAB_KEYS = TAB_STATE_KEYS;
export const TAB_LIST_KEYS = TAB_KEYS;
export const TAB_PANEL_KEYS = [...TAB_LIST_KEYS, "tabId"] as const;
