import * as ApiKey from './api-key';
import * as AppBundle from './app-bundle';
import * as AppDefinition from './app-definition';
import * as AppInstallation from './app-installation';
import * as AppUpload from './app-upload';
import * as Asset from './asset';
import * as AssetKey from './asset-key';
import * as BulkAction from './bulk-action';
import * as ContentType from './content-type';
import * as EditorInterface from './editor-interface';
import * as Entry from './entry';
import * as Environment from './environment';
import * as EnvironmentAlias from './environment-alias';
import * as Extension from './extension';
import * as Http from './http';
import * as Locale from './locale';
import * as Organization from './organization';
import * as OrganizationInvitation from './organization-invitation';
import * as OrganizationMembership from './organization-membership';
import * as PersonalAccessToken from './personal-access-token';
import * as PreviewApiKey from './preview-api-key';
import * as Release from './release';
import * as ReleaseAction from './release-action';
import * as Role from './role';
import * as ScheduledAction from './scheduled-action';
import * as Snapshot from './snapshot';
import * as Space from './space';
import * as SpaceMember from './space-member';
import * as SpaceMembership from './space-membership';
import * as Tag from './tag';
import * as Task from './task';
import * as Team from './team';
import * as TeamMembership from './team-membership';
import * as TeamSpaceMembership from './team-space-membership';
import * as Upload from './upload';
import * as Usage from './usage';
import * as User from './user';
import * as Webhook from './webhook';
declare const _default: {
    ApiKey: typeof ApiKey;
    AppBundle: typeof AppBundle;
    AppDefinition: typeof AppDefinition;
    AppInstallation: typeof AppInstallation;
    AppUpload: typeof AppUpload;
    Asset: typeof Asset;
    AssetKey: typeof AssetKey;
    BulkAction: typeof BulkAction;
    ContentType: typeof ContentType;
    EditorInterface: typeof EditorInterface;
    Entry: typeof Entry;
    Environment: typeof Environment;
    EnvironmentAlias: typeof EnvironmentAlias;
    Extension: typeof Extension;
    Http: typeof Http;
    Locale: typeof Locale;
    Organization: typeof Organization;
    OrganizationInvitation: typeof OrganizationInvitation;
    OrganizationMembership: typeof OrganizationMembership;
    PersonalAccessToken: typeof PersonalAccessToken;
    PreviewApiKey: typeof PreviewApiKey;
    Release: typeof Release;
    ReleaseAction: typeof ReleaseAction;
    Role: typeof Role;
    ScheduledAction: typeof ScheduledAction;
    Snapshot: typeof Snapshot;
    Space: typeof Space;
    SpaceMember: typeof SpaceMember;
    SpaceMembership: typeof SpaceMembership;
    Tag: typeof Tag;
    Task: typeof Task;
    Team: typeof Team;
    TeamMembership: typeof TeamMembership;
    TeamSpaceMembership: typeof TeamSpaceMembership;
    Upload: typeof Upload;
    Usage: typeof Usage;
    User: typeof User;
    Webhook: typeof Webhook;
};
export default _default;
